-- liquibase formatted sql

-- ========================================
-- ENUM TYPES
-- ========================================
-- changeset lms.admin:01:set student-status-enum
-- This enum is used to represent the status of a student in the system.
-- It can be 'active', 'inactive', or 'graduated'.
CREATE TYPE student_status AS ENUM ('active', 'inactive', 'graduated');


-- ========================================
-- STUDENTS
-- ========================================

-- changeset lms.admin:02-create-students-table
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    date_of_birth DATE,
    gender VARCHAR(10),
    enrollment_date DATE NOT NULL,
    status student_status DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ========================================
-- INSTRUCTORS
-- ========================================

-- changeset lms.admin:03-create-instructors-table
CREATE TABLE instructors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    department VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ========================================
-- COURSES
-- ========================================

-- changeset lms.admin:04-create-courses-table
CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR(10) NOT NULL UNIQUE,
    course_name VARCHAR(100) NOT NULL,
    description TEXT,
    credits INT NOT NULL CHECK (credits > 0),
    instructor_id BIGINT REFERENCES instructors(id),
    schedule JSONB,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ========================================
-- ENROLLMENTS
-- ========================================

-- changeset lms.admin:05-create-enrollments-table
CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    enrollment_date DATE DEFAULT CURRENT_DATE,
    status VARCHAR(20) DEFAULT 'active',
    CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_enrollments_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT unique_enrollment UNIQUE (student_id, course_id)
);

-- ========================================
-- ATTENDANCE
-- ========================================

-- changeset lms.admin:06-create-attendance-table
CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    session_date DATE NOT NULL,
    status VARCHAR(10) NOT NULL CHECK (status IN ('present', 'absent', 'late')),
    recorded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attendance_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_attendance_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT unique_attendance UNIQUE (student_id, course_id, session_date)
);

-- ========================================
-- GRADES
-- ========================================

-- changeset lms.admin:07-create-grades-table
CREATE TABLE grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    grade VARCHAR(5) NOT NULL,
    comments TEXT,
    graded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_grades_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_grades_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT unique_grade UNIQUE (student_id, course_id)
);
